on: [push]

name: AZCliRGCheck_ARMDeploy

jobs:

  AZCli-CheckRGExists:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Azure CLI script file
      id: azcliscript
      uses: azure/CLI@v1
      env:
        rgName: arm-actions
        rgLocation: westeurope
      with:
        azcliversion: 2.0.72
        inlineScript: |
          if [ $(az group exists --name $rgName) = false ]; then az group create --name $rgName --location $rgLocation; fi

  build-and-deploy:
    needs: AZCli-CheckRGExists
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Master 
      uses: actions/checkout@master

    - name: ARM Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: arm Deploy
    #   uses: azure/arm-deploy@v1
    #   with:
    #     subscriptionId: ${{ secrets.SUB_ID }}
    #     resourceGroupName: ${{  steps.azcliscript.env.rgName  }}
    #     template: ./virtualMachine/arm/SimpleVM1/deploy.json
    #     parameters: ./virtualMachine/arm/SimpleVM1/parameters1.json

    - name: Deploy ARM template
      env:
        RESOURCE_GROUP: {{steps.azcliscript.env.rgName}}
        ARM_FILE: ./virtualMachine/arm/SimpleVM1/deploy.json
        PARAM_FILE: ./virtualMachine/arm/SimpleVM1/parameters1.json
        LOCATION: {{steps.azcliscript.env.rglocation}}
      run: |
        az deployment sub create --location ${LOCATION} --template-file ${ARM_FILE} --parameters @${PARAM_FILE}
