on: 
  push:
    paths:
    - 'virtualMachine/arm/SimpleVM1/**'

env:
  AZURE_LOCATION: westeurope
  AZURE_RG: arm-actions

name: AZCliRGCheck_ARMDeploy2

jobs:

  AZCli-CheckRGExists:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Azure CLI script file
      id: azcliscript
      uses: azure/CLI@v1
      env:
        rgName: arm-actions
        rgLocation: westeurope
      with:
        azcliversion: 2.0.72
        inlineScript: |
          if [ $(az group exists --name ${{ env.AZURE_RG }}) = false ]; then az group create --name ${{ env.AZURE_RG }} --location ${{ env.AZURE_LOCATION }}; fi

  cli-build-and-deploy:
    needs: AZCli-CheckRGExists
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Master 
      uses: actions/checkout@master

    - name: ARM Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy with AZ CLI commands
      env:
        ARM_FILE: ./virtualMachine/arm/SimpleVM1/deploy1.json
        PARAM_FILE: ./virtualMachine/arm/SimpleVM1/parameters1.json
        DEPLOY_NAME: deploy-(date +%s)
      run: |
        now=$(date +"%d_%m_%Y_%ss")
        deploy=deploy
        deployment="${deploy}-${now}"
        az group deployment create --name ${deployment} --resource-group ${{ env.AZURE_RG }} --template-file ${ARM_FILE} --parameters @${PARAM_FILE}