on: 
  push:
    paths:
    - 'virtualMachine/arm/SimpleVM1/**'
name: SimpleVMBuild

jobs:
  ResourceGroupCheck:
    runs-on: windows-latest
    steps:
    
    - name: Login via Az module
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true 
        
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      env:
        rgName: arm-actions
        rgLocation: westeurope
      with:
        inlineScript: |
          Get-AzVM -ResourceGroupName "$rgName"
        azPSVersion: '3.1.0'

  build-and-deploy:
    needs: ResourceGroupCheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Master 
      uses: actions/checkout@master
    - name: ARM Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: arm Deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.SUB_ID }}
        resourceGroupName: github-action-arm-rg
        template: ./virtualMachine/arm/SimpleVM1/deploy.json
        parameters: ./virtualMachine/arm/SimpleVM1/parameters1.json
